### ISSUE TITLE
How to fix issue:  User-Password or CHAP-Password/CHAP-Challenge missing

### ISSUE THREAD

**Issue by monkeyk** [ctran/TinyRadius#12]
Exception full stack:

org.tinyradius.util.RadiusException: Access-Request: User-Password or CHAP-Password/CHAP-Challenge missing
	at org.tinyradius.packet.AccessRequest.decodeRequestAttributes(AccessRequest.java:186)
	at org.tinyradius.packet.RadiusPacket.decodePacket(RadiusPacket.java:1042)
	at org.tinyradius.packet.RadiusPacket.decodeRequestPacket(RadiusPacket.java:632)
	at org.tinyradius.util.RadiusServer.makeRadiusPacket(RadiusServer.java:574)
	at org.tinyradius.util.RadiusServer.processRequest(RadiusServer.java:427)
	at org.tinyradius.util.RadiusServer.listen(RadiusServer.java:381)
	at org.tinyradius.util.RadiusServer.listenAuth(RadiusServer.java:338)
	at org.tinyradius.util.RadiusServer$1.run(RadiusServer.java:141)

**Comment by JeppeLeth** [comment]
I have this problem too. Using a Cisco router

**Comment by Nivani** [comment]
I have this problem too because the router I'm using is trying to use EAP to authenticate instead of simple RADIUS username/password or CHAP.
